/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import estructuras.Hashtable;
import estructuras.ArbolBB;
import estructuras.NodoArbol;
import estructuras.ListaSimple;
import estructuras.NodoSimple;
import estructuras.ProcesadorArchivo;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;

/**
 *
 * @author Diego Linares, Luis Peña y Luis Lovera
 */
public class Interfaz1 extends javax.swing.JFrame {
    private ProcesadorArchivo procesador;
    private Hashtable tabla;
    private ArbolBB arbol;
    private boolean datosCargados;

    /*
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        initComponents();
        procesador = new ProcesadorArchivo();
        tabla = new Hashtable();
        arbol = new ArbolBB();
        datosCargados=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new gui.FondoInterfaz();
        cargarArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mostrarPatrones = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        verPatronMenosFrecuente = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reiniciar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        verInfoPatron1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        verListaPatrones = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        verPatronMasFrecuente1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarArchivo.setBackground(new java.awt.Color(255, 204, 153));
        cargarArchivo.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N
        cargarArchivo.setText("Cargar archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 140, -1));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Identificación y Análisis de Secuencias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel2.setText("Presione el botón para cargar el archivo con la información relativa a la secuencia de ADN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 17));

        mostrarPatrones.setBackground(new java.awt.Color(255, 204, 153));
        mostrarPatrones.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N
        mostrarPatrones.setText("Mostrar patrones");
        mostrarPatrones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPatronesActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarPatrones, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 140, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 2));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 830, 50));

        verPatronMenosFrecuente.setBackground(new java.awt.Color(255, 224, 193));
        verPatronMenosFrecuente.setColumns(20);
        verPatronMenosFrecuente.setRows(5);
        jScrollPane2.setViewportView(verPatronMenosFrecuente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 260, 40));

        jLabel4.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel4.setText("Presione el botón para mostrar todos los patrones encontrados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 17));

        jLabel5.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Patrón menos frecuente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 200, 17));

        reiniciar.setBackground(new java.awt.Color(255, 204, 153));
        reiniciar.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 140, -1));

        jLabel6.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lista de patrones ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 140, 17));

        jLabel8.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Búsqueda específica");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 180, 17));

        jLabel7.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Patrón más frecuente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 140, 17));

        verInfoPatron1.setBackground(new java.awt.Color(255, 224, 193));
        verInfoPatron1.setColumns(20);
        verInfoPatron1.setRows(5);
        jScrollPane3.setViewportView(verInfoPatron1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 240, -1));

        verListaPatrones.setBackground(new java.awt.Color(255, 224, 193));
        verListaPatrones.setColumns(20);
        verListaPatrones.setRows(5);
        jScrollPane4.setViewportView(verListaPatrones);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 830, -1));

        verPatronMasFrecuente1.setBackground(new java.awt.Color(255, 224, 193));
        verPatronMasFrecuente1.setColumns(20);
        verPatronMasFrecuente1.setRows(5);
        jScrollPane5.setViewportView(verPatronMasFrecuente1);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 260, 40));

        jLabel9.setFont(new java.awt.Font("Avenir Next Condensed", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Búsqueda general de patrones");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 180, 17));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarPatronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPatronesActionPerformed
        // TODO add your handling code here:
        try{
            if (arbol.esVacio()) {
                procesador.construirArbol(tabla, arbol);
            }
            
            ListaSimple<String> listaPatrones = arbol.inorden();
            verListaPatrones.setText(listaPatrones.mostrarLista());
            verListaPatrones.setCaretPosition(0);
            
            NodoArbol patronMayor = arbol.buscarMayorFrecuencia();
            verPatronMasFrecuente1.setText(patronMayor.getPatron());
            
            NodoArbol patronMenor = arbol.buscarMenorFrecuencia();
            verPatronMasFrecuente1.setText(patronMenor.getPatron());
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al mostrar patrones: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mostrarPatronesActionPerformed

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        // TODO add your handling code here:
        try{
            
            if (datosCargados){
                JOptionPane.showMessageDialog(this, "Por favor, presione el botón 'Reiniciar' antes de cargar otro archivo.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;   
            }
            
            JFileChooser archivo = new JFileChooser();
            archivo.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));

            int result = archivo.showOpenDialog(this);
            
            if (result == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = archivo.getSelectedFile();
      
                if (archivoSeleccionado==null || !archivoSeleccionado.exists()){
                    JOptionPane.showMessageDialog(this, "No seleccionaste ningún archivo.","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    if (procesador.leerArchivo(archivoSeleccionado)){
                        procesador.construirTabla(tabla);
                        procesador.detectorSobrantes();
                        datosCargados=true;
                        JOptionPane.showMessageDialog(this, "Datos cargados con éxito.","Carga de archivo",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
                
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error. Intente de nuevo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        tabla=new Hashtable();
        procesador=new ProcesadorArchivo();
        datosCargados=false;
    }//GEN-LAST:event_reiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton mostrarPatrones;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextArea verInfoPatron1;
    private javax.swing.JTextArea verListaPatrones;
    private javax.swing.JTextArea verPatronMasFrecuente1;
    private javax.swing.JTextArea verPatronMenosFrecuente;
    // End of variables declaration//GEN-END:variables
}
